project_id = "yjohojrcekdskzhaxedm"

[functions.register-concert]
verify_jwt = false

[functions.chatbot-concert]
verify_jwt = false

[functions.generate-ticket]
verify_jwt = false

[functions.download-ticket]
verify_jwt = false